"""
"Index of /" artifact generator.
Apache-style directory listing of files changed in a release.
Visual reference: 0100101110101101.org's "Index of /~you"
"""

from .artifact_base import html_wrap, escape_html, format_date_short, format_size, generate_artifact_meta


def generate(release):
    """Generate an Apache directory listing artifact for a release."""
    meta = generate_artifact_meta(release, "index_of")
    files = release.get("compare", {}).get("files", [])
    tag = release["tag"]
    date_str = format_date_short(release["published_at"])

    dirs = {}
    for f in files:
        parts = f["filename"].split("/")
        if len(parts) > 1:
            d = parts[0] + "/"
        else:
            d = "./"
        if d not in dirs:
            dirs[d] = {"files": [], "total_add": 0, "total_del": 0}
        dirs[d]["files"].append(f)
        dirs[d]["total_add"] += f["additions"]
        dirs[d]["total_del"] += f["deletions"]

    rows_html = ""
    rows_html += _row("../", "", "-", date_str, "parent")

    for dirname in sorted(dirs.keys()):
        info = dirs[dirname]
        n = len(info["files"])
        rows_html += _row(
            dirname,
            f"{n} items",
            format_size(info["total_add"] + info["total_del"]),
            date_str,
            "dir",
        )

    for f in sorted(files, key=lambda x: x["filename"])[:200]:
        status_icon = {"added": "+", "removed": "×", "modified": "~", "renamed": "→"}.get(f["status"], "?")
        rows_html += _row(
            f["filename"],
            f'<span class="status status-{f["status"]}">{status_icon}</span>',
            format_size(f["additions"] + f["deletions"]),
            date_str,
            "file",
        )

    stats = release.get("stats", {})
    stats_line = " | ".join(
        f"{v} {k.replace('_', ' ')}" for k, v in stats.items() if v
    )

    body = f"""
    <div class="listing">
        <h1>Index of /hermes-agent/{tag}/</h1>
        <div class="meta">{stats_line}</div>
        <table>
            <thead>
                <tr>
                    <th class="name">Name</th>
                    <th class="status-col">Status</th>
                    <th class="size">Size</th>
                    <th class="date">Last Modified</th>
                </tr>
            </thead>
            <tbody>
                <tr class="sep"><td colspan="4"><hr></td></tr>
{rows_html}
                <tr class="sep"><td colspan="4"><hr></td></tr>
            </tbody>
        </table>
        <div class="footer">
            hermes-agent/{tag} — {len(files)} entries — generated by Hermes Archaeology Museum
        </div>
    </div>
    """

    css = """
        body {
            background: #f5f5f0;
            color: #222;
            font-family: 'Courier New', Courier, monospace;
            font-size: 13px;
            padding: 20px 30px;
        }
        .listing { max-width: 1100px; }
        h1 {
            font-size: 18px;
            font-weight: normal;
            margin-bottom: 4px;
            color: #111;
        }
        .meta {
            font-size: 11px;
            color: #666;
            margin-bottom: 16px;
            letter-spacing: 0.5px;
        }
        table { width: 100%; border-collapse: collapse; }
        th {
            text-align: left;
            font-weight: normal;
            color: #555;
            padding: 2px 12px 2px 0;
            font-size: 12px;
            border-bottom: 1px solid #ccc;
        }
        td { padding: 1px 12px 1px 0; white-space: nowrap; }
        .name { width: 60%; }
        .status-col { width: 10%; text-align: center; }
        .size { width: 15%; text-align: right; }
        .date { width: 15%; text-align: right; color: #888; }
        tr.sep td { padding: 0; }
        hr { border: none; border-top: 1px solid #ccc; }
        a {
            color: #1a0dab;
            text-decoration: none;
        }
        a:hover { text-decoration: underline; }
        a.dir { color: #006621; }
        a.parent { color: #666; }
        .status { font-weight: bold; font-size: 14px; }
        .status-added { color: #2a7; }
        .status-removed { color: #d44; }
        .status-modified { color: #b80; }
        .status-renamed { color: #66b; }
        tr:hover { background: #eeeee8; }
        .footer {
            margin-top: 16px;
            font-size: 11px;
            color: #999;
            border-top: 1px solid #ddd;
            padding-top: 8px;
        }
    """

    return html_wrap(
        f"Index of /hermes-agent/{tag}/",
        body,
        css=css,
        meta={"artifact-type": "index_of", "release-tag": tag},
    ), meta


def _row(name, status, size, date, cls="file"):
    display = escape_html(name)
    return f"""                <tr>
                    <td class="name"><a class="{cls}" href="#">{display}</a></td>
                    <td class="status-col">{status}</td>
                    <td class="size">{size}</td>
                    <td class="date">{date}</td>
                </tr>
"""
